import Head from 'next/head'
import Image from 'next/image'
import { Inter } from 'next/font/google'
import { Navbar,Sidebar,Content } from '..'
import styles from '../styles/index.module.css'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      
      </Head>
      {/* grid grid-cols-6 grid-rows-2  bg-gray-100 */}
      <main className={` w-full `}>
        <div className={`${styles.grid} w-full md:hidden sm:hidden font-perso font-light`}>

       <Sidebar/>
       <Navbar/>
       <Content/>
        </div>
      </main>
    </>
  )
}
